language: python
matrix:
  include:
    - env: TOX_ENV=py310
      python: "3.10"
    - env: TOX_ENV=py311
      python: "3.11"
    - env: TOX_ENV=py312
      python: "3.12"
    - env: TOX_ENV=lint
install: pip install tox
script: tox -e $TOX_ENV
cache: pip
